"""
Module: schemas.update_event

Description:
Schémas Pydantic pour les événements de mise à jour des monstres
"""

from pydantic import BaseModel, Field
from typing import List, Optional, Dict, Any
from datetime import datetime


class UpdateEventBase(BaseModel):
    """Base pour les événements d'update"""

    actor_type: str = Field(..., description="admin|system|user")
    actor_name: str = Field(..., description="Nom de l'acteur")
    actor_id: Optional[str] = None
    source: str = Field(..., description="Origine de l'update (ex: admin_endpoint)")
    reason: Optional[str] = None
    validation_before: bool
    validation_after: bool
    skip_validation: bool = False
    storage_mode_before: str = Field(..., description="json|structured")
    storage_mode_after: str = Field(..., description="json|structured")
    changed_fields: List[str] = Field(default_factory=list)
    diff_payload: Optional[Dict[str, Dict[str, Any]]] = None
    request_context: Optional[Dict[str, Any]] = None


class UpdateEvent(UpdateEventBase):
    """Événement d'update complet"""

    id: int
    monster_state_db_id: int
    occurred_at: datetime

    class Config:
        from_attributes = True


class UpdateEventSchema(BaseModel):
    """Schéma pour les événements d'update (compatible Pydantic v2)"""

    id: int
    monster_state_db_id: int
    occurred_at: datetime
    actor_type: str
    actor_name: str
    actor_id: Optional[str] = None
    source: str
    reason: Optional[str] = None
    validation_before: bool
    validation_after: bool
    skip_validation: bool
    storage_mode_before: str
    storage_mode_after: str
    changed_fields: List[str]
    diff_payload: Optional[Dict[str, Any]] = None
    request_context: Optional[Dict[str, Any]] = None

    class Config:
        from_attributes = True


class TimelineEvent(BaseModel):
    """Événement de la timeline unifiée (transitions + updates)"""

    event_type: str = Field(..., description="state_transition|data_update")
    happened_at: datetime
    actor: str
    summary: str
    details: Dict[str, Any] = Field(default_factory=dict)

    class Config:
        json_schema_extra = {
            "example": {
                "event_type": "data_update",
                "happened_at": "2026-03-10T15:30:00Z",
                "actor": "admin_user",
                "summary": "Updated 4 fields",
                "details": {
                    "changed_fields": ["stats.hp", "stats.atk"],
                    "validation_before": True,
                    "validation_after": True,
                    "reason": "Admin correction",
                },
            }
        }


class MonsterHistory(BaseModel):
    """Historique complet d'un monstre"""

    monster_id: str
    current_state: str
    timeline: List[TimelineEvent] = Field(default_factory=list)

    class Config:
        json_schema_extra = {
            "example": {
                "monster_id": "uuid-123",
                "current_state": "APPROVED",
                "timeline": [
                    {
                        "event_type": "state_transition",
                        "happened_at": "2026-03-10T10:00:00Z",
                        "actor": "system",
                        "summary": "Monster generated",
                        "details": {
                            "from_state": None,
                            "to_state": "GENERATED",
                            "note": "Auto-generated by Gemini",
                        },
                    }
                ],
            }
        }
