"""ajout table skill_images

Revision ID: e615d174e9f2
Revises: c4f8b21d9a63
Create Date: 2026-07-22 22:18:00.136219

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'e615d174e9f2'
down_revision = 'c4f8b21d9a63'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skill_images',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('source_monster_image_id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=False),
    sa.Column('raw_image_key', sa.String(), nullable=True),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_monster_image_id'], ['monster_images.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skill_images_id'), 'skill_images', ['id'], unique=False)
    op.create_index(op.f('ix_skill_images_skill_id'), 'skill_images', ['skill_id'], unique=False)
    op.create_index(op.f('ix_skill_images_source_monster_image_id'), 'skill_images', ['source_monster_image_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_skill_images_source_monster_image_id'), table_name='skill_images')
    op.drop_index(op.f('ix_skill_images_skill_id'), table_name='skill_images')
    op.drop_index(op.f('ix_skill_images_id'), table_name='skill_images')
    op.drop_table('skill_images')
    # ### end Alembic commands ###
