"""ChangeRangRankAndNomName

Revision ID: 65adb29cc7c0
Revises: a1b2c3d4e5f6
Create Date: 2026-04-02 19:11:09.174898

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy import text

# revision identifiers, used by Alembic.
revision = '65adb29cc7c0'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # add new columns as nullable to allow data migration
    op.add_column('monsters', sa.Column('name', sa.String(), nullable=True))
    op.add_column(
        'monsters',
        sa.Column(
            'rank',
            sa.Enum('COMMON', 'RARE', 'EPIC', 'LEGENDARY', 'UNKNOWN', name='rankenum'),
            nullable=True,
        ),
    )

    # copy data from old columns to new columns
    op.execute(text("UPDATE monsters SET name = nom WHERE nom IS NOT NULL"))
    op.execute(text("UPDATE monsters SET rank = rang WHERE rang IS NOT NULL"))

    # set new columns to non-nullable now that data is copied
    op.alter_column('monsters', 'name', nullable=False)
    op.alter_column('monsters', 'rank', nullable=False)

    # recreate indexes and drop old ones/columns
    op.drop_index(op.f('ix_monsters_nom'), table_name='monsters')
    op.drop_index(op.f('ix_monsters_rang'), table_name='monsters')
    op.create_index(op.f('ix_monsters_name'), 'monsters', ['name'], unique=False)
    op.create_index(op.f('ix_monsters_rank'), 'monsters', ['rank'], unique=False)
    op.drop_column('monsters', 'nom')
    op.drop_column('monsters', 'rang')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # add old columns as nullable so we can move data back
    op.add_column(
        'monsters',
        sa.Column('rang', sa.Enum('COMMON', 'RARE', 'EPIC', 'LEGENDARY', name='rankenum'), nullable=True),
    )
    op.add_column('monsters', sa.Column('nom', sa.VARCHAR(), nullable=True))

    # copy data back from new columns to old ones
    op.execute(text("UPDATE monsters SET nom = name WHERE name IS NOT NULL"))
    op.execute(text("UPDATE monsters SET rang = rank WHERE rank IS NOT NULL"))

    # set old columns non-nullable to match previous schema
    op.alter_column('monsters', 'nom', nullable=False)
    op.alter_column('monsters', 'rang', nullable=False)

    # swap indexes and drop new columns
    op.drop_index(op.f('ix_monsters_rank'), table_name='monsters')
    op.drop_index(op.f('ix_monsters_name'), table_name='monsters')
    op.create_index(op.f('ix_monsters_rang'), 'monsters', ['rang'], unique=False)
    op.create_index(op.f('ix_monsters_nom'), 'monsters', ['nom'], unique=False)
    op.drop_column('monsters', 'rank')
    op.drop_column('monsters', 'name')
    # ### end Alembic commands ###
