"""baseline

Revision ID: 8c4a1471dee3
Revises: 
Create Date: 2026-02-15 19:19:07.226739

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '8c4a1471dee3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monsters_state',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('monster_id', sa.String(), nullable=False),
    sa.Column('state', sa.Enum('GENERATED', 'DEFECTIVE', 'CORRECTED', 'PENDING_REVIEW', 'APPROVED', 'TRANSMITTED', 'REJECTED', name='monsterstateenum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('monster_data', sa.JSON(), nullable=True),
    sa.Column('generated_by', sa.String(), nullable=False),
    sa.Column('generation_prompt', sa.Text(), nullable=True),
    sa.Column('is_valid', sa.Boolean(), nullable=False),
    sa.Column('validation_errors', sa.JSON(), nullable=True),
    sa.Column('reviewed_by', sa.String(), nullable=True),
    sa.Column('review_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('transmitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('transmission_attempts', sa.Integer(), nullable=False),
    sa.Column('last_transmission_error', sa.Text(), nullable=True),
    sa.Column('invocation_api_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monsters_state_id'), 'monsters_state', ['id'], unique=False)
    op.create_index(op.f('ix_monsters_state_monster_id'), 'monsters_state', ['monster_id'], unique=True)
    op.create_index(op.f('ix_monsters_state_state'), 'monsters_state', ['state'], unique=False)
    op.create_table('monsters',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('monster_state_id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(), nullable=False),
    sa.Column('element', sa.Enum('FIRE', 'WATER', 'WIND', 'EARTH', 'LIGHT', 'DARKNESS', name='elementenum'), nullable=False),
    sa.Column('rang', sa.Enum('COMMON', 'RARE', 'EPIC', 'LEGENDARY', name='rankenum'), nullable=False),
    sa.Column('hp', sa.Float(), nullable=False),
    sa.Column('atk', sa.Float(), nullable=False),
    sa.Column('def_', sa.Float(), nullable=False),
    sa.Column('vit', sa.Float(), nullable=False),
    sa.Column('description_carte', sa.Text(), nullable=False),
    sa.Column('description_visuelle', sa.Text(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['monster_state_id'], ['monsters_state.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monsters_element'), 'monsters', ['element'], unique=False)
    op.create_index(op.f('ix_monsters_id'), 'monsters', ['id'], unique=False)
    op.create_index(op.f('ix_monsters_monster_state_id'), 'monsters', ['monster_state_id'], unique=True)
    op.create_index(op.f('ix_monsters_nom'), 'monsters', ['nom'], unique=False)
    op.create_index(op.f('ix_monsters_rang'), 'monsters', ['rang'], unique=False)
    op.create_table('state_transitions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('monster_state_db_id', sa.Integer(), nullable=False),
    sa.Column('from_state', sa.Enum('GENERATED', 'DEFECTIVE', 'CORRECTED', 'PENDING_REVIEW', 'APPROVED', 'TRANSMITTED', 'REJECTED', name='monsterstateenum'), nullable=True),
    sa.Column('to_state', sa.Enum('GENERATED', 'DEFECTIVE', 'CORRECTED', 'PENDING_REVIEW', 'APPROVED', 'TRANSMITTED', 'REJECTED', name='monsterstateenum'), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actor', sa.String(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['monster_state_db_id'], ['monsters_state.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_state_transitions_id'), 'state_transitions', ['id'], unique=False)
    op.create_index(op.f('ix_state_transitions_monster_state_db_id'), 'state_transitions', ['monster_state_db_id'], unique=False)
    op.create_table('monster_images',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('monster_id', sa.Integer(), nullable=False),
    sa.Column('image_name', sa.String(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=False),
    sa.Column('raw_image_key', sa.String(), nullable=True),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['monster_id'], ['monsters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monster_images_id'), 'monster_images', ['id'], unique=False)
    op.create_index(op.f('ix_monster_images_monster_id'), 'monster_images', ['monster_id'], unique=False)
    op.create_table('skills',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('monster_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('damage', sa.Float(), nullable=False),
    sa.Column('cooldown', sa.Float(), nullable=False),
    sa.Column('lvl_max', sa.Float(), nullable=False),
    sa.Column('rank', sa.Enum('COMMON', 'RARE', 'EPIC', 'LEGENDARY', name='rankenum'), nullable=False),
    sa.Column('ratio_stat', sa.String(), nullable=False),
    sa.Column('ratio_percent', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['monster_id'], ['monsters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skills_id'), 'skills', ['id'], unique=False)
    op.create_index(op.f('ix_skills_monster_id'), 'skills', ['monster_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_skills_monster_id'), table_name='skills')
    op.drop_index(op.f('ix_skills_id'), table_name='skills')
    op.drop_table('skills')
    op.drop_index(op.f('ix_monster_images_monster_id'), table_name='monster_images')
    op.drop_index(op.f('ix_monster_images_id'), table_name='monster_images')
    op.drop_table('monster_images')
    op.drop_index(op.f('ix_state_transitions_monster_state_db_id'), table_name='state_transitions')
    op.drop_index(op.f('ix_state_transitions_id'), table_name='state_transitions')
    op.drop_table('state_transitions')
    op.drop_index(op.f('ix_monsters_rang'), table_name='monsters')
    op.drop_index(op.f('ix_monsters_nom'), table_name='monsters')
    op.drop_index(op.f('ix_monsters_monster_state_id'), table_name='monsters')
    op.drop_index(op.f('ix_monsters_id'), table_name='monsters')
    op.drop_index(op.f('ix_monsters_element'), table_name='monsters')
    op.drop_table('monsters')
    op.drop_index(op.f('ix_monsters_state_state'), table_name='monsters_state')
    op.drop_index(op.f('ix_monsters_state_monster_id'), table_name='monsters_state')
    op.drop_index(op.f('ix_monsters_state_id'), table_name='monsters_state')
    op.drop_table('monsters_state')
    # ### end Alembic commands ###
