"""Add monster_update_events table

Revision ID: 20260310_1500-a1b2c3d4e5f6
Revises: 20260215_2155-b17dd08352b7
Create Date: 2026-03-10 15:00:00.000000

"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "20260310_1500-a1b2c3d4e5f6"
down_revision = "20260215_2155-b17dd08352b7"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "monster_update_events",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("monster_state_db_id", sa.Integer(), nullable=False),
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("actor_type", sa.String(), nullable=False),
        sa.Column("actor_name", sa.String(), nullable=False),
        sa.Column("actor_id", sa.String(), nullable=True),
        sa.Column("source", sa.String(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("validation_before", sa.Boolean(), nullable=False),
        sa.Column("validation_after", sa.Boolean(), nullable=False),
        sa.Column("skip_validation", sa.Boolean(), nullable=False),
        sa.Column("storage_mode_before", sa.String(), nullable=False),
        sa.Column("storage_mode_after", sa.String(), nullable=False),
        sa.Column("changed_fields", sa.JSON(), nullable=False),
        sa.Column("diff_payload", sa.JSON(), nullable=True),
        sa.Column("request_context", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["monster_state_db_id"],
            ["monsters_state.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_monster_update_events_id"),
        "monster_update_events",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_monster_update_events_monster_state_db_id"),
        "monster_update_events",
        ["monster_state_db_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_monster_update_events_occurred_at"),
        "monster_update_events",
        ["occurred_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_monster_update_events_occurred_at"), table_name="monster_update_events"
    )
    op.drop_index(
        op.f("ix_monster_update_events_monster_state_db_id"),
        table_name="monster_update_events",
    )
    op.drop_index(
        op.f("ix_monster_update_events_id"), table_name="monster_update_events"
    )
    op.drop_table("monster_update_events")
    # ### end Alembic commands ###
