"""add_monster_uuid

Revision ID: dc7e24653278
Revises: 8c4a1471dee3
Create Date: 2026-02-15 19:22:13.519761

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'dc7e24653278'
down_revision = '8c4a1471dee3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('monsters', sa.Column('monster_uuid', sa.String(), nullable=False))
    op.create_index(op.f('ix_monsters_monster_uuid'), 'monsters', ['monster_uuid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_monsters_monster_uuid'), table_name='monsters')
    op.drop_column('monsters', 'monster_uuid')
    # ### end Alembic commands ###
